add CI/CD
fuskovic/networker pull request #4
Opened 2022-04-04 13:24 UTC by jftuga

This PR allows GitHub Actions to use `goreleaser` to automatically build Release binaries for you.

Notes:

* This only occurs when a `tag` is created with a command set like: 

```shell
CURRENT=1.0.1
git tag -a "v${CURRENT}" -m "releasing version ${CURRENT}"
git push origin "v${CURRENT}"
```
* This also creates a `draft` release which allows you to review it before publishing to a full release.

2022-04-05 01:49 UTC, fuskovic requested changes
Thanks for hooking this up.

2022-04-05 01:49 UTC, fuskovic commented on .github/workflows/release.yml
> +      - "*"
Let's change the event listener temporarily just so we can see this run before merging.

```suggestion
on:
  pull_request:
    branches: [ master ]
```

We can change it back after.

2022-04-05 03:57 UTC, fuskovic commented
@jftuga it didn't trigger.

2022-04-05 10:57 UTC, jftuga commented
> @jftuga it didn't trigger.

By default, including pull_request only runs on these activity types: opened, reopened, and synchronize.  I added a few more types, so hopefully it will trigger now.

2022-04-06 01:23 UTC, fuskovic commented
> > @jftuga it didn't trigger.
> 
> By default, including pull_request only runs on these activity types: opened, reopened, and synchronize. I added a few more types, so hopefully it will trigger now.

I've used that event listener at work on our core repos and several of my other personal repos. I know from experience that the `pull_request` event listener configured the way I originally suggested should should trigger on every new commit to the PR.

Even w/the types you added, `synchronize` should have the same behavior.

If you can get it to trigger so we can see this thing run and everything checks out I'm all for it.

2022-04-07 12:32 UTC, jftuga commented
I also submitted this idea to another go project.  They accepted my `PR `without changes.  Check out their release page:

https://github.com/s0md3v/Smap

Another idea I had was to simply remove `on:` so that you could run it manually.

2022-04-07 13:32 UTC, fuskovic commented
> I also submitted this idea to another go project. They accepted my `PR `without changes. Their `.goreleaser` and `release.yml` files are the same that I submitted to you.
> 
> Check out their release page:
> 
> https://github.com/s0md3v/Smap
> 
> Another idea I had was to simply remove `on:` so that you could run it manually.

Ok cool. In that case just change it back to what you had originally and we'll get it in and try it out. I have a [major version release](https://github.com/fuskovic/networker/pull/5) coming soon and I can take it for a spin then.

2022-04-07 20:55 UTC, jftuga commented
I have reverted this back to the original.

2022-04-07 20:57 UTC, fuskovic approved these changes

2022-04-07 20:57 UTC, merged